// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqYrA6pVTEdHbJX6zWaDFG5eAsP8MGxgo',
    appId: '1:552265431568:web:15f8044e27d394790e6895',
    messagingSenderId: '552265431568',
    projectId: 'project1-lapakbantul',
    authDomain: 'project1-lapakbantul.firebaseapp.com',
    storageBucket: 'project1-lapakbantul.firebasestorage.app',
    measurementId: 'G-ZNED0XP8KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCbK_ImxpueM9YSHtXFOItIIxaNz_K-y8',
    appId: '1:552265431568:android:51eeefbfbeecbf700e6895',
    messagingSenderId: '552265431568',
    projectId: 'project1-lapakbantul',
    storageBucket: 'project1-lapakbantul.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqYrA6pVTEdHbJX6zWaDFG5eAsP8MGxgo',
    appId: '1:552265431568:web:f9de97938fecd9560e6895',
    messagingSenderId: '552265431568',
    projectId: 'project1-lapakbantul',
    authDomain: 'project1-lapakbantul.firebaseapp.com',
    storageBucket: 'project1-lapakbantul.firebasestorage.app',
    measurementId: 'G-8XMXEYZWGZ',
  );

}